name: Build and test
on: push
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v2.3.1

      - name: Install and Build 🔧 
        run: |
          yarn install
          yarn build
          yarn test
          yarn lint